title: 南京朱梅律师个人博客
tagline: '记录我的律师执业历程'
description: '南京,律师'
url: zhumeilawyer.com
name: zhumei 
email: zhumeilawyer@163.com
encoding: utf-8
ASSETS_PATH : http://zhumeilawyer.qiniudn.com

ipygments: true
comments: true
#markdown: kramdown
markdown: redcarpet
safe: true
lsi: false

redcarpet:
  extensions:
    - with_toc_data
    - hard_wrap
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    
paginate: 5

scholar:
  bibliography_template: "%{reference}"

#kramdown:
#  input: GFM
