title: 南京朱梅律师个人博客
tagline: 'Time to understand the world'
description: 'Geographer, environmental scientist, cyclist'
url: zhumeilawyer.com
name: zhumei 
email: zhumeilawyer@163.com
encoding: utf-8
ASSETS_PATH : http://zhumeilawyer.qiniudn.com

ipygments: true
comments: true
markdown: redcarpet
paginate: 5

scholar:
  bibliography_template: "%{reference}"


