title: ZZZ
tagline: 'Time to understand the world'
description: 'Geographer, environmental scientist, cyclist'
url: http://192.168.10.195:4000
name: ZZZ
email: zhumeilawyer@163.com


ipygments: true
comments: true 
markdown: redcarpet
paginate: 5

scholar:
  bibliography_template: "%{reference}"


